src/components/navigation/navigation-item/NavigationItem.tsx, src/utils/index.ts
remove indexedText property that kept values from title, description, type and time and use more specific search logic to filter-out navigation items from list on search.
The changes can be made with "ternary operators" but implementation with "If then" more readable. 
Notes:
1) displayTitle and displayDescription converged to "string" for avoid case when displayTitle or displayDescription are numbers and .toLowerCase() will throw an error.
2) /([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/ regex - check if search query contains "m:ss"/"mm:ss" mask to filter navigation items by startTime (case "hh:mm:ss" also covered).
=> FEV-802 - Player V7 |Navigation 2.1.0| - Search results do not match the search value

src/navigation-plugin.tsx, src/utils/index.ts
use player enums to define plugin expand mode
=> Player V7| |Navigation 2.1.0| - Edit page - Navigation plugin's kitchen sink pushes the video instead of be opened on top of it

src/components/navigation/icons/EmptyList.scss, src/components/navigation/icons/EmptyList.tsx
Add text in the 'No Results' slate according to design:
https://app.zeplin.io/project/5e5faf732d13a9120d1af1e0/screen/5ea52d909d340b2399b15afc
=> Player V7| |Navigation 2.1.0| - UI - Missing text in the 'No Results' slate

src/components/navigation-search/navigation-search.tsx, src/navigation-plugin.tsx
From Dana Raviv comments:
- Search input should be focused after user clicked on navigation icon (from mouse OR keyboard);
- Accessibly should not be changed - search input should be Active (with blue border) only if search input got a focus by keyboard (by click on navigation icon from keyboard, tabing to search input by Tab key, click on clear-input icon by keyboard);
=> FEV-748 - Player V7| Navigation - When opening from the navigation icon the search field is not focused in

src/components/navigation/autoscroll-button/autoscroll-button.scss, src/components/navigation/autoscroll-button/autoscroll-button.tsx, src/components/navigation/autoscroll-button/index.ts, src/components/navigation/navigation.tsx, src/components/navigation/navigaton.scss
add tooltip to autoscroll button according to design
design: https://app.zeplin.io/project/5e5faf732d13a9120d1af1e0/screen/5edf3a7f62bac5b54deaeae1
=> FEV-756 - Player V7| Navigation 0.0.4| - No tooltip is displayed while hovering over the auto-scroll button

src/navigation-plugin.tsx
1) Add "AnswerOnAir" filter to AnswerOnAir quepoint types.
According to Jira ticket - only `Answer on Air` type of aoaMessages should be rendered by Navigation plugin. Logic of parsing aoaMessages messages been taken from QNA project (https://github.com/kaltura/playkit-js-qna/blob/e9acee4d44c0efca6d94a31469dbba21c1919a37/src/qnaPushNotification.ts#L257-L278)
2) tiny reformat with prettier;
=> FEV-791 - Live entries - All question types and announcements are displayed in the Navigation plugin

src/navigation-plugin.tsx, src/utils/index.ts
1) for live entries use absolute time of quepoints for seek and highlight;
2) use id3Tag to define initial `_currentTimeLive`;
3) increase `_currentTimeLive` every second and update `_currentTimeLive` once new `TIMED_METADATA` handled;
=> FEV-847 - Navigation quepoints got incorrect start-time after DVR window moved

src/navigation-plugin.tsx
1) for live entries without DVR disable seek;
2) prevent filtering on navigation quepoint for non-DVR entries;
=> fix(fev-891): non-dvr - prevent seek; don't filter quepoints

src/navigation-plugin.tsx
remove navigation panel on media switch
=> fix(FEV-1344): When clicking in order to go to the next entry at the playlist, the navigation and playlist buttons are being duplicated.

src/navigation-plugin.tsx
The issue happens when playlist plugin executes `this.sidePanelsManager.deactivateItem(key)` before player got ready and ui-managers doesn’t calculate player area properly.
=> fix(FEV-1407): open side panel only after player got ready

src/utils/index.ts
add missed properties to filter-out duplication for slides (https://github.com/kaltura/playkit-js-navigation/blob/master/src/utils/index.ts#L162-L169)
=> fix(FEV-1388): When broadcasting slide in preview and then go live, the slide appear duplicated in navigation plugin.

src/components/navigation/index.tsx, src/components/navigation/navigation-item/NavigationItem.scss, src/components/navigation/navigation-item/NavigationItem.tsx, src/utils/index.ts
1) don't render slides that hasn't loaded image;
2) disable auto-scroll feature (https://kaltura.atlassian.net/browse/FEV-804);
3) fix groups of navigation items for live entries;
=> fix(FEV-1322): slides that were broadcasted prior to the archive appears without images in the navigation plugin

src/navigation-plugin.tsx
**the issue:**
navigation plugin is showing on player when playing live content even when there's no data.
**the root cause:**
when media is loaded and player is live we call this._createNavigationPlugin().
**description of changes:**
remove invoking _createNavigationPlugin() when media is loaded.
once the plugin gets data, we either way call _createOrUpdatePlugin().
Solves FEV-1492
=> fix(FEV-1492): navigation plugin showing on Live entries even without chapters

src/navigation-plugin.tsx
**the issue:**
after playback ends and hitting replay/seeking to time=0, the last cuepoint in navigation panel remains highlighted.
**root cause:**
activeCues map is not being reset, so the last cp remains the active one.
**solution:**
- listen to playback_ended event
- once playback has ended, listen once to play event
- reset map and update navigation plugin
Solves [FEV-1561](https://kaltura.atlassian.net/browse/FEV-1561)
=> fix(FEV-1561): last slide is highlighted although it shouldn't be

src/components/navigation/icons/EmptyList.tsx, src/components/navigation/navigation-list/NavigationList.tsx
navigation root div has `aria-live="polite"` so list of navigation-items doesn't need another one aria-live
=> fix(FEV-1589): Screen reader (jaws) repeating the content/items inside navigation plugin twice - from top to bottom and from bottom to top

package.json, src/components/navigation/navigation-item/NavigationItem.tsx, src/components/navigation/navigation-list/NavigationList.tsx, yarn.lock
**the issue:**
Jaws screen reader guides the user to use arrow keyboards to navigate throughout the items inside navigation body, which is currently not supported.
**solution:**
- upgrade common repo
- implement usage of up and down arrow keyboards
- discard usage of translates in navigation item
Solves [FEV-1588](https://kaltura.atlassian.net/browse/FEV-1588)
=> fix(FEV-1588): use the arrow keys by Jaws screen reader is not available inside navigation

package.json, src/components/navigation-filter/navigation-filter.tsx, yarn.lock
**the issue:**
JAWS screen reader is guiding to use up/down arrows keyboard in order to navigate between the filter bar items.
**solution:**
add the ability to use up/down arrows keyboard for the filter bar navigation. 
Solves [FEV-1588](https://kaltura.atlassian.net/browse/FEV-1588)
[FEV-1588]: https://kaltura.atlassian.net/browse/FEV-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEV-1588]: https://kaltura.atlassian.net/browse/FEV-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEV-1588): add up/down arrow keyboards navigation to the filter bar

.github/workflows/common_test.yml, cypress/e2e/navigation.cy.ts, package.json, src/components/close-button/index.tsx, src/components/error/error.tsx, src/components/navigation-filter/navigation-filter.tsx, src/components/navigation-search/navigation-search.tsx, src/components/navigation/autoscroll-button/autoscroll-button.tsx, src/components/navigation/index.tsx, src/components/navigation/navigation-item/NavigationItem.tsx, src/components/navigation/plugin-button/index.tsx, src/index.ts, src/navigation-plugin.tsx, yarn.lock
The transition animation is broken when the side panel is activated
solve [FEV-1623](https://kaltura.atlassian.net/browse/FEV-1623)
fix transition animation
import from @playkit-js/common only components that Navigation plugin uses
dependent PR: https://github.com/kaltura/playkit-js-common/pull/10
[FEV-1623]: https://kaltura.atlassian.net/browse/FEV-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEV-1623): The transition animation is broken when the side panel is activated

src/components/navigation/navigation-item/QuizTitle.scss
for xs player size, in navigation side panel for quiz items- the question state label ("answered", "correct", "incorrect") should be rendered in a new line, rather than next to the question title (i.e. "Question 1").
Solves [FEC-13097](https://kaltura.atlassian.net/browse/FEC-13097)
[FEC-13097]: https://kaltura.atlassian.net/browse/FEC-13097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEC-13097): IVQ in Navigation - for xs player, the "Answered" tag should be in a new line

translations/es.i18n.json
Added missing translation to some strings in Spanish
Solves [SUP-37655](https://kaltura.atlassian.net/browse/SUP-37655)
[SUP-37655]: https://kaltura.atlassian.net/browse/SUP-37655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-37655): missing spanish translations for ivq (FEC-37655)

translations/es.i18n.json
Added some missing strings in the Spanish translation
solves [SUP-37655](https://kaltura.atlassian.net/browse/SUP-37655)
[SUP-37655]: https://kaltura.atlassian.net/browse/SUP-37655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-37655): missing spanish translations for ivq

src/navigation-plugin.tsx
**the issue:**
when `visible` configuration is set to `false`, markers are not displayed on timeline.
**root cause:**
doing `return` in `loadMedia` in a case where `visible=false`, which prevents from the rest of the flow to happen, such as registering and receiving cuepoints.
**solution:**
- not stopping the rest of the flow in `loadMedia`- just printing a log to console for debugging purpose.
- prevent rendering the side panel in another place.
Solves [FEC-13305](https://kaltura.atlassian.net/browse/FEC-13305)
[FEC-13305]: https://kaltura.atlassian.net/browse/FEC-13305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEC-13305): markers are unavailable when visible is false

cypress/e2e/navigation.cy.ts, src/components/navigation/index.tsx, src/navigation-plugin.tsx
add support to click events from timeline service-
- toggle side panel
- focus to a specific tab by cuepoint type
related PR- https://github.com/kaltura/playkit-js-timeline/pull/16
Solves [FEC-13318](https://kaltura.atlassian.net/browse/FEC-13318)
[FEC-13318]: https://kaltura.atlassian.net/browse/FEC-13318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FEC-13318): support click event from timeline service

src/components/navigation/navigation-item/NavigationItem.tsx
**issue:**
when the chapter has short title the more button is not displayed even if the chapter has a description. 
in addition, when there is no title on the chapter, only a description, nothing is displayed.
**root cause:**
the expandable-text calculate the size of the element per the text (the title from the chapter), so in case the title is short size of the element is appropriate so we doesn't create the more button.
**solution:**
send the title + description as the text to expandable-text
=> fix(SUP-39657): Latest V7 Update Does not Display Description in Chapters

src/components/navigation/plugin-button/index.tsx
**issue:**
When embed player in a form element and click on the plugin button, the page refreshes.
**solution:**
add type=button on the plugin button
solves [SUP-39294](https://kaltura.atlassian.net/browse/SUP-39294)
[SUP-39294]: https://kaltura.atlassian.net/browse/SUP-39294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-39294): Page refreshes after clicking on player buttons

src/components/navigation/plugin-button/index.tsx, src/index.ts, src/navigation-plugin.tsx
**fix: Wrong and inconsistent order of plugins**
**fix: Plugins buttons sometimes display with the wrong icon**
**solves: [FEC-13517](https://kaltura.atlassian.net/browse/FEC-13517) [FEC-13517](https://kaltura.atlassian.net/browse/FEC-13517)**
[FEC-13517]: https://kaltura.atlassian.net/browse/FEC-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEC-13517]: https://kaltura.atlassian.net/browse/FEC-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/kaltura/playkit-js-ui-managers/pull/51
https://github.com/kaltura/playkit-js-transcript/pull/175
https://github.com/kaltura/playkit-js-share/pull/38
https://github.com/kaltura/playkit-js-moderation/pull/74 …
=> fix(FEC-13517): Wrong and inconsistent order of plugins

src/navigation-plugin.tsx
https://github.com/kaltura/playkit-js-transcript/pull/192
https://github.com/kaltura/playkit-js-qna/pull/342
https://github.com/kaltura/playkit-js-ui-managers/pull/52
[FEC-13889]: https://kaltura.atlassian.net/browse/FEC-13889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEC-13889): Download_close being reported too many times to application events

cypress/e2e/navigation.cy.ts, src/components/navigation-filter/navigation-filter.tsx, src/components/navigation/navigation-list/NavigationList.tsx
**Issue:**
Screen reader announces the radio button role for the Tab/Tab list items (All, Chapters, Slides, Hotspots) radio role is not appropriate here.
**Fix:**
Change the "radio" to "tab" and "radiogroup" to "tablist", add also role "tabpanel" in the div that display the items for each tab.
Solves [ADA-1501](https://kaltura.atlassian.net/browse/ADA-1501)
[ADA-1501]: https://kaltura.atlassian.net/browse/ADA-1501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ADA-1501): [By Applause] Screen Reader: Core Player: Tab/Tab listitems are identified as as Radio buttons by screen reader.

src/components/navigation/navigation-item/NavigationItem.tsx
Change the role of navigation items to "button", since this is a clickable and there is no indication for that.
solves [ADA-1407](https://kaltura.atlassian.net/browse/ADA-1407)
[ADA-1407]: https://kaltura.atlassian.net/browse/ADA-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ADA-1407): [Strategic Blue / University of Sheffield] - Button element has the wrong role

src/components/navigation/navigation-item/NavigationItem.tsx
Issue:
aria-hidden item attribute was set on a focusable div.
Fix:
Removing the redundant attribute.
=> fix(ADA-1390): Removing aria-hidden from focusable items.

src/navigation-plugin.tsx
issue:
on timeline when using special characters like & and " it wasn't display correctly
solution:
navigation plugin prepared the cuepoint and did decoding for the title before display it on navigation, so use this for timeline also.
solved [SUP-45356](https://kaltura.atlassian.net/browse/SUP-45356)
[SUP-45356]: https://kaltura.atlassian.net/browse/SUP-45356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-45356): [Minn State] Issue with Special Characters in Chapter Titles Display on the Player

cypress/e2e/navigation.cy.ts, src/components/navigation/navigation-item/NavigationItem.tsx, translations/en.i18n.json
Change the times in the  aria-label of navigation items to be read as a text with hours/minutes/seconds.
Using the duration-humanizer implementation was added here - https://github.com/kaltura/playkit-js-ui/pull/955
Solves [ADA-1988](https://kaltura.atlassian.net/browse/ADA-1988)
[ADA-1988]: https://kaltura.atlassian.net/browse/ADA-1988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ADA-1988): Change time to be read as text

src/components/navigation/plugin-button/index.tsx
This solves https://kaltura.atlassian.net/browse/ADA-1736. 
It sets the Tooltip position to always be bottom-left.
=> fix(ADA-1736): Tooltip strict position
