kaltura/playkit-js-navigation

- src/utils/index.ts
Inline expression become too complicated for maintenance
I suggest use couple of `if` conditions instead
> chore(ui): hot fix for isDataEqual method

- src/components/navigation/icons/EmptyList.tsx
- src/components/navigation/navigation-list/NavigationList.tsx
- src/components/navigation/navigation.tsx
Show "No results" text only if search input contains text
> FEV-849 - Show "No result text" only if search input contains text

- package-lock.json
- package.json
- src/components/navigation/plugin-button/plugin-button.scss
- src/components/navigation/plugin-button/plugin-button.tsx
- src/navigation-plugin.tsx
Change plugin icon styles according to design:
Designs: https://app.zeplin.io/project/5d8a2d0fcae74a026ea3adf2/screen/5da703e07d2c9f17760004a7
**Related contrib changes:**
https://github.com/kaltura/playkit-js-contrib/pull/336
> FEV-796 - Player V7| |Navigation 2.1.0| - UI - Icons on the upper menu are not as designed

- src/navigation-plugin.tsx
1) `TIMED_METADATA` event doesn't triggered in Safari on seek, it causes an issue when navigation items filtered out (uses new player.currentTime and outdated currentTimeLive). The changes update currentTimeLive by calculated seek time difference.
2) prevent seek less than 1s on navigation item click.
> fix(fev-858): use calculated value to update currentTimeLive on seek

- src/navigation-plugin.tsx
for VOD entries initialize plugin UI only if navigation content exist
> fix(fev-747): add plugin UI only when VOD content exist

- src/navigation-plugin.tsx
set KS only after media loaded hook triggered
> fix(FEV-859): slides doesn't appear in kitchen sink 

- package-lock.json
- src/components/navigation/navigation-item/NavigationItem.tsx
- src/navigation-plugin.tsx
- src/utils/index.ts
filter out all slides which are duplication of their adjacent previous slides 
(happens while switching from preview to live mode on the webcast app)
solves: FEV-861
> fix(FEV-861): player v7 Duplicate slide is displayed on the kitchen sink when moving from preview to live

- commitlint.config.js
- src/components/navigation-filter/navigation-filter.tsx
- src/components/navigation-search/navigation-search.tsx
- src/components/navigation/navigation-item/NavigationItem.scss
- src/components/navigation/navigation-item/NavigationItem.tsx
- src/components/navigation/navigation.tsx
- src/components/navigation/plugin-button/plugin-button.tsx
> fix(FEV-1028): fix more a11y issues

- src/navigation-plugin.tsx
- src/utils/index.ts
fetch baseThumbAssetUrl from BE
> fix(FEV-1249): Kaltura CuePoints loads thumb assets always with KS

- package.json
- yarn.lock
> fix(FEV-1548): when tab navigate to Read more\less buttons and hit space\enter the chapter is also triggered

- package.json
- src/components/navigation/plugin-button/index.tsx
- src/components/navigation/plugin-button/plugin-button.scss
- src/navigation-plugin.tsx
- yarn.lock
1) update ui-manager;
2) add more plugin support;
> feat(FEV-1553): Add support to the More plugin

- src/components/navigation-filter/navigation-filter.tsx
- src/components/navigation/navigation-item/NavigationItem.tsx
- src/components/navigation/navigation-list/NavigationList.tsx
> fix(FEV-1590): Mac voice over issues

- cypress/e2e/navigation.cy.ts
- package.json
- src/components/navigation/index.tsx
- src/components/navigation/plugin-button/index.tsx
- src/navigation-plugin.tsx
- yarn.lock
1) handle focus change on plugin close;
2) upd tests
> fix(FEC-12918): When users close a menu by clicking the close button, focus should go back to the button that opened the plugin

- src/components/navigation-filter/navigation-filter.tsx
- src/components/navigation/navigation-item/NavigationItem.tsx
- add aria label to tabs in the filter bar, i.e. for All -> list all, for chapters -> list chapters
- add aria label to more/less button -> "Read more/less about this slide/chapter"
Solves [FEC-12919](https://kaltura.atlassian.net/browse/FEC-12919)
[FEC-12919]: https://kaltura.atlassian.net/browse/FEC-12919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-12919): add aria labels

- package.json
> chore: upd playkit-kaltura-cuepoints

- package.json
- src/components/navigation/icons/IconsFactory.tsx
- src/components/navigation/index.tsx
- src/navigation-plugin.tsx
- src/types/navigation-item-data.ts
- src/utils/index.ts
- translations/en.i18n.json
- yarn.lock
- add quiz tab to filter bar
related PR- https://github.com/kaltura/playkit-js-common/pull/14
Solves [FEC-13059](https://kaltura.atlassian.net/browse/FEC-13059)
*was previously FEV-1634
[FEC-13059]: https://kaltura.atlassian.net/browse/FEC-13059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FEC-13059): add quiz tab to filter bar

- src/components/navigation/icons/EmptyState.tsx
- translations/en.i18n.json
- translations/es.i18n.json
issue
when the search list is empty, there is hard coded message that need to be translated
solution
change emptyState to support translation
> fix(SUP-37265):navigation plugin is translated only partly

- cypress/e2e/navigation.cy.ts
- package.json
- src/components/navigation-filter/navigation-filter.tsx
- src/components/navigation/navigation-item/NavigationItem.tsx
- yarn.lock
add tests to search result and screenReaderWrapper component.
**dependent on PR in common-** https://github.com/kaltura/playkit-js-common/pull/18
Solves [FEC-13157](https://kaltura.atlassian.net/browse/FEC-13157)
[FEC-13157]: https://kaltura.atlassian.net/browse/FEC-13157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13157): add tests to search result and screenReaderWrapper component

- cypress/e2e/env.ts
- cypress/e2e/navigation.cy.ts
- package.json
- src/components/navigation/navigation-list/NavigationList.tsx
- src/navigation-plugin.tsx
- src/types/navigation-item-data.ts
- yarn.lock
solves: https://kaltura.atlassian.net/browse/FEC-13179
1) handle external onClick handler
2) upd and fix e2e tests
> fix(FEC-13179): when navigating in the quiz to a question in the KS it's not changing the question in the overlay 

- cypress/e2e/navigation.cy.ts
- src/components/navigation/navigation-item/NavigationItem.tsx
solves: https://kaltura.atlassian.net/browse/FEC-13469
solves: https://kaltura.atlassian.net/browse/FEC-13470
> fix(FEC-13470) title-description issues (FEC-13469)

- src/components/navigation/navigation-item/NavigationItem.scss
resolves: https://kaltura.atlassian.net/browse/FEC-13535
> fix(FEC-13535): "More" buttons position doesn't match figma's.

- src/navigation-plugin.tsx
prevent click on navigation item for live media without dvr
Resolves: https://kaltura.atlassian.net/browse/FEC-13766
> fix(FEC-13766): prevent seek for live entry without DVR

- package.json
- translations/de.i18n.json
- yarn.lock
Add missing German translation
solves [SUP-42574](https://kaltura.atlassian.net/browse/SUP-42574)
[SUP-42574]: https://kaltura.atlassian.net/browse/SUP-42574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-42574): Navigation Overlay is Missing German translation

- package.json
- src/components/navigation/plugin-button/index.tsx
- yarn.lock
resolves: https://kaltura.atlassian.net/browse/ADA-1787
> fix(ADA-1787): nvda a11y fix

- src/navigation-plugin.tsx
related PR https://github.com/kaltura/playkit-js-timeline/pull/45/files
> fix(CR-152): use timeline API

- package.json
[FEC-14328](https://kaltura.atlassian.net/browse/FEC-14328)
[FEC-14328]: https://kaltura.atlassian.net/browse/FEC-14328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FEC-14328): Player v7 | Add timeline as a dependency of navigation plugin

- src/navigation-plugin.tsx
This solves this https://kaltura.atlassian.net/browse/ADA-2704. Here I am passing the Hotspot title to the timeline cue point.
Related to https://github.com/kaltura/playkit-js-timeline/pull/56.
> Fix(ADA-2704) - Pass title to cue point
